# Uncomment the next line to define a global platform for your project
 platform :ios, '8.0'

target 'TransAlt' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for TransAlt
  pod 'Firebase/Core'
  pod 'Firebase/Crash'
  pod 'Firebase/Messaging'
  pod 'Firebase/Performance'

  end

  target 'TransAltTests' do
    inherit! :search_paths
    # Pods for testing

  end
